#!/bin/bash

# Update and install python3-pip
sudo apt-get update
sudo apt-get install python3-pip -y

# Install Python packages using pip3
pip3 install pandas
pip3 install openpyxl
pip3 install pyarrow
