# CONSTANTS

# ENDPOINTS
API_BASE = "/api/v2/"
# SECURITY CLASSIFICATIONS
ENDPOINT_SECURITY_CLASSIFICATIONS = API_BASE + "security-classifications"
# ASSETS
ENDPOINT_ASSETS = API_BASE + "assets"
# BUSINESS UNITS
ENDPOINT_BUSINESS_UNIT = API_BASE + "business-units"
# LIBRARIES
ENDPOINT_LIBRARIES = API_BASE + "libraries"
# COMPONENTS
ENDPOINT_COMPONENTS = API_BASE + "components"
# CUSTOM FIELDS
ENDPOINT_CUSTOM_FIELDS = API_BASE + "custom-fields"
ENDPOINT_CUSTOM_FIELDS_TYPES = ENDPOINT_CUSTOM_FIELDS + "/types"
ENDPOINT_CUSTOM_FIELDS_GROUPS = ENDPOINT_CUSTOM_FIELDS + "/groups"
# TRUST ZONES
ENDPOINT_TRUST_ZONES = API_BASE + "trust-zones"
# LIBRARIES
ENDPOINT_LIBRARIES = API_BASE + "libraries"
# COMPONENTS
ENDPOINT_COMPONENTS = API_BASE + "components"
ENDPOINT_COMPONENTS_CATEGORIES_SUMMARY = ENDPOINT_COMPONENTS + "/categories/summary"
